import RequestProject.NANC.Gate1B.V10HistoricalResidual
import RequestProject.NANC.Gate1B.V10CanonicalZeroMode

/-!
# V10 · Gate 1B — the E-indeterminacy counterguards

These are **finite perturbation identities**, not metadata.  They exist to stop a
later compiler from silently deducing `E(q) = M_q` from the nonzero-frequency
theorem of `V10CanonicalZeroMode.lean`.

* `weightedResidual_perturbation` : moving the historical expected term by `T` at
  a single `q₀` of the family moves the residual by exactly `T · λ(q₀)`.
* `switchedOperator_perturbation` : the same perturbation moves the project's own
  switched operator by exactly `−T · λ₃(U,V;q₀)`.
* `historical_residual_not_determined_by_nonzero_packet` : consequently, with `E`
  left arbitrary the historical sum is **not** determined by the canonical
  (nonzero-frequency) data.
* `zero_mean_fails_for_arbitrary_comparison` : the canonical unit mean is the only
  centring that kills the additive zero mode.

Nothing here proves or disproves `E = M`; it proves that the *nonzero packet
cannot decide it*.
-/

namespace TwinPrimeProject
namespace Gate1BV10

open Finset Gate01Switch

/-- The perturbed expected function: `E' q = E q + T` at `q₀`, unchanged
elsewhere. -/
noncomputable def perturbedExpected (E : ℕ → ℝ) (q0 : ℕ) (T : ℝ) : ℕ → ℝ :=
  Function.update E q0 (E q0 + T)

@[simp] theorem perturbedExpected_self (E : ℕ → ℝ) (q0 : ℕ) (T : ℝ) :
    perturbedExpected E q0 T q0 = E q0 + T := by
  simp [perturbedExpected]

theorem perturbedExpected_of_ne (E : ℕ → ℝ) (q0 : ℕ) (T : ℝ) {q : ℕ} (h : q ≠ q0) :
    perturbedExpected E q0 T q = E q := by
  simp [perturbedExpected, Function.update_of_ne h]

/-- **The E-perturbation identity.**  `R_E(E') − R_E(E) = T · λ(q₀)`, with the
exact sign generated by the project's `weightedResidual`. -/
theorem weightedResidual_perturbation (Qset : Finset ℕ) (lam M E : ℕ → ℝ)
    {q0 : ℕ} (hq0 : q0 ∈ Qset) (T : ℝ) :
    weightedResidual Qset lam M (perturbedExpected E q0 T)
      - weightedResidual Qset lam M E = T * lam q0 := by
  classical
  simp only [weightedResidual, ← Finset.sum_sub_distrib]
  rw [Finset.sum_eq_single q0]
  · simp [perturbedExpected]; ring
  · intro q _ hq
    rw [perturbedExpected_of_ne E q0 T hq]
    ring
  · intro h; exact absurd hq0 h

/-- **The switched operator moves by exactly `−T · λ₃(U,V;q₀)`.** -/
theorem switchedOperator_perturbation (Qset : Finset ℕ) (U V K : ℕ) (c E : ℕ → ℝ)
    {q0 : ℕ} (hq0 : q0 ∈ Qset) (T : ℝ) :
    switchedOperator Qset U V K c (perturbedExpected E q0 T)
      = switchedOperator Qset U V K c E - T * lambda3 U V q0 := by
  classical
  have h1 := switchedOperator_hist_eq_can_sub_residual Qset U V K c E
    (perturbedExpected E q0 T)
  have h2 := weightedResidual_perturbation Qset (lambda3 U V) E E hq0 T
  have h3 : weightedResidual Qset (lambda3 U V) E E = 0 :=
    weightedResidual_eq_zero_of_agree Qset (lambda3 U V) E E (fun q _ => rfl)
  rw [h3, sub_zero] at h2
  rw [h1, h2]

/-- **The historical residual is not determined by the nonzero packet.**  For any
prescribed target value `t` there is an expected term differing from `E` only at
`q₀` realising it, while the canonical data (which does not mention `E` at all)
is untouched. -/
theorem historical_residual_not_determined_by_nonzero_packet
    (Qset : Finset ℕ) (lam M E : ℕ → ℝ) {q0 : ℕ} (hq0 : q0 ∈ Qset)
    (hlam : lam q0 ≠ 0) (t : ℝ) :
    ∃ E' : ℕ → ℝ, (∀ q, q ≠ q0 → E' q = E q) ∧ weightedResidual Qset lam M E' = t := by
  classical
  refine ⟨perturbedExpected E q0 ((t - weightedResidual Qset lam M E) / lam q0), ?_, ?_⟩
  · intro q hq; exact perturbedExpected_of_ne E q0 _ hq
  · have h := weightedResidual_perturbation Qset lam M E hq0
      ((t - weightedResidual Qset lam M E) / lam q0)
    rw [div_mul_cancel₀ _ hlam] at h
    linarith

/-- **Hostile test 1 (concrete).**  Changing `E` at one `q` really does change the
residual: an explicit finite instance, no hypothesis. -/
theorem residual_changes_concretely :
    weightedResidual {1} (fun _ => (1 : ℝ)) (fun _ => 0)
        (perturbedExpected (fun _ => 0) 1 1)
      ≠ weightedResidual {1} (fun _ => (1 : ℝ)) (fun _ => 0) (fun _ => 0) := by
  have h := weightedResidual_perturbation ({1} : Finset ℕ) (fun _ => (1 : ℝ))
    (fun _ => 0) (fun _ => 0) (Finset.mem_singleton_self 1) 1
  intro hEq
  rw [hEq] at h
  norm_num at h

/-- **Hostile test 2.**  The canonical unit mean is load bearing: for an arbitrary
comparison term the additive zero mode of the discrepancy does not cancel. -/
theorem zero_mean_fails_for_arbitrary_comparison (q : ℕ) [NeZero q] :
    ∃ (c M : ZMod q → ℂ), fourierCoeff (fun n => c n - M n) 0 ≠ 0 := by
  refine ⟨fun _ => 0, fun _ => 1, ?_⟩
  have h := zero_mean_fails_for_arbitrary_expected_term q
  rw [h.1]
  exact h.2

end Gate1BV10
end TwinPrimeProject
