import RequestProject.NANC.Gate01Switch.SwitchedOperator
import RequestProject.FordMaynardInterface

/-!
# V10 · Gate 1B — the historical / canonical residual identity

Everything here is stated for the project's **own** switched objects
(`TwinPrimeProject.Gate01Switch.discrMinusTwo`, `switchedOperator`, `lambda3`);
no new toy discrepancy is introduced.

Recall the banked definition

    discrMinusTwo K q c E  =  (∑_{n ≤ K, q ∣ n+2} c n) − E q  =  C_q − E(q).

Contents.

* `discr_hist_eq_can_add_gap` :  `C_q − E(q) = (C_q − M_q) + (M_q − E(q))`,
  for an **arbitrary** historical `E` and an **arbitrary** canonical `M`.
* `weightedDiscrSum_hist_eq_can_sub_residual` and
  `switchedOperator_hist_eq_can_sub_residual` :
  `S_hist = S_can − R_E` with `R_E = ∑_q λ(q) (E q − M q)`, the project's sign
  convention (identical to `Gate1B.SafeExtensions.RE`).
* `CanonicalComparisonRealisation` : the **interface** a future canonical
  comparison sequence must satisfy.  It is *not* inhabited here.
* `canonicalComparison_residual_vanishes` : the only thing that interface buys,
  derived from its literal fields.

Nothing below infers `E = M`; see `V10Counterguards.lean`.
-/

namespace TwinPrimeProject
namespace Gate1BV10

open Finset Gate01Switch

/-! ## 1. Pointwise historical/canonical split -/

/-- **Exact pointwise identity.**  `C_q − E(q) = (C_q − M_q) + (M_q − E(q))`. -/
theorem discr_hist_eq_can_add_gap (K q : ℕ) (c M E : ℕ → ℝ) :
    discrMinusTwo K q c E = discrMinusTwo K q c M + (M q - E q) := by
  simp only [discrMinusTwo]; ring

/-! ## 2. Weighted families -/

/-- The `λ`-weighted discrepancy sum over a finite `q`-family. -/
noncomputable def weightedDiscrSum (Qset : Finset ℕ) (lam : ℕ → ℝ) (K : ℕ) (c E : ℕ → ℝ) : ℝ :=
  ∑ q ∈ Qset, lam q * discrMinusTwo K q c E

/-- The source residual `R_E = ∑_q λ(q) (E q − M q)`, the project's sign
convention. -/
noncomputable def weightedResidual (Qset : Finset ℕ) (lam M E : ℕ → ℝ) : ℝ :=
  ∑ q ∈ Qset, lam q * (E q - M q)

/-- **`S_hist = S_can − R_E`.** -/
theorem weightedDiscrSum_hist_eq_can_sub_residual
    (Qset : Finset ℕ) (lam : ℕ → ℝ) (K : ℕ) (c M E : ℕ → ℝ) :
    weightedDiscrSum Qset lam K c E
      = weightedDiscrSum Qset lam K c M - weightedResidual Qset lam M E := by
  simp only [weightedDiscrSum, weightedResidual, ← Finset.sum_sub_distrib]
  refine Finset.sum_congr rfl fun q _ => ?_
  rw [discr_hist_eq_can_add_gap K q c M E]
  ring

/-- The switched operator of the bank is the `λ₃`-weighted discrepancy sum. -/
theorem switchedOperator_eq_weightedDiscrSum (Qset : Finset ℕ) (U V K : ℕ) (c E : ℕ → ℝ) :
    switchedOperator Qset U V K c E = weightedDiscrSum Qset (lambda3 U V) K c E := rfl

/-- **`S_hist = S_can − R_E` for the project's switched operator.** -/
theorem switchedOperator_hist_eq_can_sub_residual
    (Qset : Finset ℕ) (U V K : ℕ) (c M E : ℕ → ℝ) :
    switchedOperator Qset U V K c E
      = switchedOperator Qset U V K c M
        - weightedResidual Qset (lambda3 U V) M E := by
  rw [switchedOperator_eq_weightedDiscrSum, switchedOperator_eq_weightedDiscrSum,
    weightedDiscrSum_hist_eq_can_sub_residual]

/-- If the historical and canonical centrings coincide on the family, the
residual vanishes.  (One direction only: see the counterguards.) -/
theorem weightedResidual_eq_zero_of_agree (Qset : Finset ℕ) (lam M E : ℕ → ℝ)
    (h : ∀ q ∈ Qset, E q = M q) : weightedResidual Qset lam M E = 0 := by
  refine Finset.sum_eq_zero fun q hq => ?_
  rw [h q hq, sub_self, mul_zero]

/-! ## 3. The canonical comparison interface (uninhabited) -/

/-- The canonical local main term generated by a global comparison sequence
`b_can`: the same fixed shift `2` progression as the physical count. -/
noncomputable def canonicalMainOfComparison (bcan : ℕ → ℝ) (K q : ℕ) : ℝ :=
  ∑ n ∈ residueMinusTwoSet K q, bcan n

/-- **OPEN SOURCE INTERFACE — deliberately left uninhabited.**

A realisation of the canonical comparison: a global comparison sequence `b_can`
whose local counts on the fixed-shift progression `q ∣ n + 2` reproduce the
historical expected term `E` on the whole `q`-family, together with the
project's Ford–Maynard comparison-source conditions.  Nothing in this project
constructs such a sequence. -/
structure CanonicalComparisonRealisation (Qset : Finset ℕ) (K : ℕ) (E : ℕ → ℝ) where
  /-- The global canonical comparison sequence. -/
  bcan : ℕ → ℝ
  /-- The exact local main-term identity, on the fixed shift `2`. -/
  localMainTerm : ∀ q ∈ Qset, E q = canonicalMainOfComparison bcan K q
  /-- The Ford–Maynard transference conditions attached to the comparison. -/
  fordConditions : ShiftedMobiusBank.FordProjectTransferenceConditions
  /-- The comparison-sequence condition of the Ford–Maynard interface holds. -/
  comparisonSequence : fordConditions.comparisonSequence
  /-- The shift is the fixed shift, never averaged. -/
  fixedShift : fordConditions.fixedShift

/-- **The only consequence drawn from the interface**: its literal fields make
the historical residual against the canonical comparison main term vanish. -/
theorem canonicalComparison_residual_vanishes
    {Qset : Finset ℕ} {K : ℕ} {E : ℕ → ℝ} (R : CanonicalComparisonRealisation Qset K E)
    (lam : ℕ → ℝ) :
    weightedResidual Qset lam (canonicalMainOfComparison R.bcan K) E = 0 :=
  weightedResidual_eq_zero_of_agree Qset lam _ E R.localMainTerm

/-- With a realisation in hand the historical switched operator *is* the
canonical one.  Conditional: the realisation is never supplied. -/
theorem switchedOperator_hist_eq_can_of_realisation
    {Qset : Finset ℕ} {K : ℕ} {E : ℕ → ℝ} (R : CanonicalComparisonRealisation Qset K E)
    (U V : ℕ) (c : ℕ → ℝ) :
    switchedOperator Qset U V K c E
      = switchedOperator Qset U V K c (canonicalMainOfComparison R.bcan K) := by
  rw [switchedOperator_hist_eq_can_sub_residual Qset U V K c
      (canonicalMainOfComparison R.bcan K) E,
    canonicalComparison_residual_vanishes R (lambda3 U V), sub_zero]

end Gate1BV10
end TwinPrimeProject
