import Gate1B.HStarK0J0DeterminantShell

/-!
# Gate 1B · the HSTAR `k = 0`, `J = ∅` template type and template **families**

**Finite data and finite algebra only.**

A *template* is one discrete branch of the HSTAR first parent, decorated with
its source factors, its dyadic support, its Perron index, its two scale
parameters `Y₁, Y₂`, its determinant-shell data and its expected-term data.

A *family* is a finite indexed collection of templates together with nuclear
coefficients.  §3 proves that a single template is **not** the same datum as a
family: the scope distinction is kernel-checked, and no theorem of this bank
identifies them.
-/

namespace TwinPrimeProject
namespace CurrentProgramme
namespace HStarTemplates

open Finset

/-! ## 1. Expected-term data -/

/-- Expected-term data of one template.  The shift is the literal fixed `2`. -/
structure ExpectedTermData where
  /-- The coefficient of the expected (main) term. -/
  coefficient : ℂ
  /-- The fixed shift, pinned to `2`. -/
  shift : ℕ
  shift_eq : shift = 2

/-! ## 2. One template -/

/-- One HSTAR `k = 0`, `J = ∅` template. -/
structure HStarK0J0Template where
  /-- The discrete branch. -/
  branch : HStarEndpointBranch
  /-- The `u`-side source kind. -/
  uKind : HStarSourceKind
  /-- The `v`-side source kind. -/
  vKind : HStarSourceKind
  /-- Dyadic support of the `u`-side. -/
  uSupport : DyadicSupport
  /-- Dyadic support of the `v`-side. -/
  vSupport : DyadicSupport
  /-- The Perron decoration (finite index only). -/
  perron : PerronParameterIndex
  /-- The first scale parameter. -/
  Y1 : ℕ
  /-- The second scale parameter. -/
  Y2 : ℕ
  /-- Determinant-shell data of the template. -/
  shell : DeterminantShellData
  /-- Expected-term data of the template. -/
  expected : ExpectedTermData

/-- The determinant relation attached to a template. -/
def HStarK0J0Template.DeterminantOK (T : HStarK0J0Template) : Prop :=
  T.shell.DeterminantRelation

/-- Every template whose shell satisfies `d·p·r = m·n + 2` satisfies the
determinant relation `q·ℓ − u·v = 2`. -/
theorem HStarK0J0Template.determinantOK_of_shell (T : HStarK0J0Template)
    (h : T.shell.ShellRelation) : T.DeterminantOK :=
  determinant_shell T.shell h

/-! ## 3. Families of templates -/

/-- A finite **family** of templates with nuclear coefficients. -/
structure HStarTemplateFamily where
  /-- The number of templates in the family. -/
  size : ℕ
  /-- The templates. -/
  templates : Fin size → HStarK0J0Template
  /-- The nuclear coefficient of each template. -/
  coeff : Fin size → ℂ

/-- The one-element family generated by a single template. -/
def singletonFamily (T : HStarK0J0Template) (c : ℂ) : HStarTemplateFamily where
  size := 1
  templates := fun _ => T
  coeff := fun _ => c

@[simp] theorem singletonFamily_size (T : HStarK0J0Template) (c : ℂ) :
    (singletonFamily T c).size = 1 := rfl

/-- A concrete template, used only as a witness in the scope firewalls. -/
def sampleTemplate : HStarK0J0Template where
  branch := HStarEndpointBranch.interior
  uKind := HStarSourceKind.squarefreeMoebiusMultiplicative
  vKind := HStarSourceKind.completelyMultiplicativeUnitTwist
  uSupport := ⟨1, 2, by norm_num⟩
  vSupport := ⟨1, 2, by norm_num⟩
  perron := ⟨0⟩
  Y1 := 1
  Y2 := 1
  shell := ⟨1, 1, 1, 1, 1⟩
  expected := ⟨0, 2, rfl⟩

/-- A second concrete template, differing from `sampleTemplate` in its branch. -/
def sampleTemplate' : HStarK0J0Template :=
  { sampleTemplate with branch := HStarEndpointBranch.leftEndpoint }

theorem sampleTemplate_ne_sampleTemplate' : sampleTemplate ≠ sampleTemplate' := by
  intro h
  have : HStarEndpointBranch.interior = HStarEndpointBranch.leftEndpoint :=
    congrArg HStarK0J0Template.branch h
  exact absurd this (by decide)

/-- The two-element family used as the scope witness. -/
def samplePairFamily : HStarTemplateFamily where
  size := 2
  templates := fun i => if i.val = 0 then sampleTemplate else sampleTemplate'
  coeff := fun _ => 1

/-- **Scope firewall (data level).**  A family is not a template: there is a
family which is not the singleton family of any template. -/
theorem exists_family_not_singleton :
    ∃ F : HStarTemplateFamily, ∀ (T : HStarK0J0Template) (c : ℂ),
      F ≠ singletonFamily T c := by
  refine ⟨samplePairFamily, fun T c h => ?_⟩
  have : (2 : ℕ) = 1 := congrArg HStarTemplateFamily.size h
  exact absurd this (by decide)

/-- The constant two-element family, agreeing with `samplePairFamily` at index
`0` only. -/
def sampleConstFamily : HStarTemplateFamily where
  size := 2
  templates := fun _ => sampleTemplate
  coeff := fun _ => 1

/-- A total accessor, so that families may be compared without dependent-type
gymnastics. -/
def HStarTemplateFamily.templateAt (F : HStarTemplateFamily) (i : ℕ) :
    Option HStarK0J0Template :=
  if h : i < F.size then some (F.templates ⟨i, h⟩) else none

/-- **Scope firewall (content level).**  One member of a family does not
determine the family: the two sample families agree at index `0` and differ at
index `1`. -/
theorem member_does_not_determine_family :
    samplePairFamily.templateAt 0 = sampleConstFamily.templateAt 0 ∧
      samplePairFamily ≠ sampleConstFamily := by
  constructor
  · rfl
  · intro h
    have h1 : samplePairFamily.templateAt 1 = sampleConstFamily.templateAt 1 :=
      congrArg (fun F => HStarTemplateFamily.templateAt F 1) h
    have e1 : samplePairFamily.templateAt 1 = some sampleTemplate' := rfl
    have e2 : sampleConstFamily.templateAt 1 = some sampleTemplate := rfl
    rw [e1, e2] at h1
    exact sampleTemplate_ne_sampleTemplate' (Option.some.inj h1).symm

end HStarTemplates
end CurrentProgramme
end TwinPrimeProject
