import RequestProject.NANC.D4.Prop44Geometry

namespace TwinPrimeProject.NANC.D4

inductive Prop44Slot | one | two | three
  deriving DecidableEq, Repr

private def slotContribution (target placed : Prop44Slot) (x : ℚ) : ℚ :=
  if target = placed then x else 0

/-- Additive lower bounds generated by placing two indivisible blocks in the
three slots. Co-located blocks therefore contribute their sum. -/
def PlacementLowerBounds (pa pb : Prop44Slot) (a b s₁ s₂ s₃ : ℚ) : Prop :=
  slotContribution .one pa a + slotContribution .one pb b ≤ s₁ ∧
  slotContribution .two pa a + slotContribution .two pb b ≤ s₂ ∧
  slotContribution .three pa a + slotContribution .three pb b ≤ s₃

/-- The arithmetic nine-case `R × L` obstruction. It assumes the placement
bounds; it does not assert that an analytic packet supplies such blocks. -/
theorem prop44_RL_no_go {ε n a b s₁ s₂ s₃ : ℚ}
    (hε : 0 ≤ ε) (ha : (5 : ℚ) / 18 ≤ a) (hb : (1 : ℚ) / 3 ≤ b)
    (hsnonneg : 0 ≤ s₁ ∧ 0 ≤ s₂ ∧ 0 ≤ s₃)
    (hprop : Prop44ExponentConditions ε n s₁ s₂ s₃)
    (pa pb : Prop44Slot)
    (hplace : PlacementLowerBounds pa pb a b s₁ s₂ s₃) : False := by
  rcases hsnonneg with ⟨hs1, hs2, hs3⟩
  rcases hprop with ⟨hp1, hp2, hp3⟩
  cases pa <;> cases pb <;>
    simp [PlacementLowerBounds, slotContribution] at hplace <;>
    rcases hplace with ⟨hl1, hl2, hl3⟩ <;> linarith

/-- Finite exponent data awaiting a source-derived packet dictionary. -/
structure PacketExponentData where
  s₁ : ℚ
  s₂ : ℚ
  s₃ : ℚ
  n : ℚ

def PassesProp44ExponentGate (ε : ℚ) (P : PacketExponentData) : Prop :=
  Prop44ExponentConditions ε P.n P.s₁ P.s₂ P.s₃

def ResidualPacket (ε : ℚ) (P : PacketExponentData) : Prop :=
  ¬ PassesProp44ExponentGate ε P

theorem packet_passes_or_residual (ε : ℚ) (P : PacketExponentData) :
    PassesProp44ExponentGate ε P ∨ ResidualPacket ε P := by
  exact Classical.em _

theorem packet_not_passes_and_residual (ε : ℚ) (P : PacketExponentData) :
    ¬ (PassesProp44ExponentGate ε P ∧ ResidualPacket ε P) := by
  tauto

theorem finite_packet_partition {ι : Type*} (S : Finset ι)
    (packet : ι → PacketExponentData) (ε : ℚ) :
    (∀ i ∈ S, PassesProp44ExponentGate ε (packet i) ∨
      ResidualPacket ε (packet i)) ∧
    (∀ i ∈ S, ¬ (PassesProp44ExponentGate ε (packet i) ∧
      ResidualPacket ε (packet i))) := by
  constructor <;> intro i hi
  · exact packet_passes_or_residual ε (packet i)
  · exact packet_not_passes_and_residual ε (packet i)

end TwinPrimeProject.NANC.D4
