import Mathlib
import RequestProject.EnergySpectrumExact
import RequestProject.CollisionProbability

/-!
# Dominant Short-Energy Conjecture: Formal Statement

## Overview

This file contains the formal definition and statement (NOT proof) of the
Dominant Short-Energy Conjecture, which is the corrected target for the
Growth-Q entropy route toward Erdős Problem #319.

## Background

The naive conjecture that primitive smooth reciprocal identities have bounded
support is FALSE (disproved in `UnboundedSupport.lean`). The corrected
framework studies the *energy spectrum* of reciprocal subset-sum collisions.

The key insight: a single long identity of support `s` is weighted by `2^{-s}`
in the entropy deficit, but exponentially many long identities can still
contribute macroscopic energy. The Dominant Short-Energy Conjecture asserts
that if the total energy is macroscopic (deficit ≥ δ), then a non-negligible
fraction must come from short-support kernel vectors.

## Definitions

For a denominator vector `q : Fin k → ℕ`:
- `energyAtSupport k q s` = number of nonzero signed kernel vectors with support `s`
  (defined in `EnergySpectrumExact.lean`)
- `shortWeightedEnergy k q C` = `Σ_{s ≤ C} E_s(Q) * 2^{-s}` (weighted short energy)
- `totalWeightedEnergy k q` = `Σ_s E_s(Q) * 2^{-s}` (total weighted energy)
  (defined in `CollisionProbability.lean`)
-/

open Finset BigOperators

noncomputable section

/-- The weighted short energy up to support bound `C`:
    `Σ_{s ≤ C} E_s(Q) / 2^s`. -/
def shortWeightedEnergy (k : ℕ) (q : Fin k → ℕ) (C : ℕ) : ℚ :=
  ∑ s ∈ Finset.range (C + 1), (energyAtSupport k q s : ℚ) / 2 ^ s

/-- `y`-smooth denominator: all prime factors are at most `y`. -/
def isSmooth (y n : ℕ) : Prop :=
  ∀ p : ℕ, p.Prime → p ∣ n → p ≤ y

/-- A denominator vector is `y`-smooth if all entries are `y`-smooth. -/
def allSmooth (k : ℕ) (q : Fin k → ℕ) (y : ℕ) : Prop :=
  ∀ i : Fin k, isSmooth y (q i)

/--
**Dominant Short-Energy Conjecture** (NOT proved).

For fixed smoothness parameter `y` and every `δ > 0`, there exist constants
`C` (support bound) and `c > 0` (energy lower bound) such that for every
`y`-smooth denominator vector `q` with `k` entries:

  If `totalWeightedEnergy k q ≥ δ`,
  then `shortWeightedEnergy k q C ≥ c`.

Equivalently: if the entropy deficit `D(Q) ≥ log₂(1 + δ)` is non-negligible,
then a non-negligible portion of the collision energy comes from kernel vectors
of bounded support.

**Mathematical significance:**
- This would imply that high-entropy-deficit sets contain "short" reciprocal
  identities, even though individual primitive identities can have unbounded support.
- Combined with a realization theorem (showing dense `P` can represent small
  rational targets), this would contribute to the Growth-Q branch of Erdős #319.

**Main danger:**
A single long identity of support `s` contributes `2^{-s}` to energy, but
exponentially many (say `2^{0.95s}`) long identities could produce macroscopic
total energy without any short identities. The conjecture asserts this cannot
happen for smooth denominators.
-/
theorem dominantShortEnergy_conjecture
    (y : ℕ) (δ : ℚ) (hδ : 0 < δ) :
    ∃ C : ℕ, ∃ c : ℚ, 0 < c ∧
    ∀ k : ℕ, ∀ q : Fin k → ℕ,
      (∀ i, q i ≠ 0) →
      allSmooth k q y →
      totalWeightedEnergy k q ≥ δ →
      shortWeightedEnergy k q C ≥ c := by
  -- This is a CONJECTURE, not a theorem. It is left as sorry to indicate
  -- that it has not been proved. See the docstring for mathematical context.
  sorry

/--
**Weaker variant: Shortest-Vector Conjecture** (NOT proved).

If the entropy deficit is positive, then there exists at least one nonzero
kernel vector of support at most `C(y, δ)`.

This is strictly weaker than the Dominant Short-Energy Conjecture:
the dominant conjecture requires the *total weighted short energy* to be
bounded below, not just the existence of one short vector.
-/
theorem shortestVector_conjecture
    (y : ℕ) (δ : ℚ) (hδ : 0 < δ) :
    ∃ C : ℕ,
    ∀ k : ℕ, ∀ q : Fin k → ℕ,
      (∀ i, q i ≠ 0) →
      allSmooth k q y →
      totalWeightedEnergy k q ≥ δ →
      ∃ s, s ≤ C ∧ 0 < energyAtSupport k q s := by
  sorry

end

/-!
## What would be needed to prove the Dominant Short-Energy Conjecture

### Known approaches (all incomplete):

1. **Graver basis / integer kernel approach**: For `y`-smooth denominators,
   the integer weights `L/q` lie in a lattice generated by products of
   `π(y)` primes. Graver basis theory bounds the support of primitive
   elements, but standard bounds depend on the magnitude of entries
   (exponentially large here), not just the number of primes.

2. **p-adic layer peeling**: At each prime `p ≤ y`, elements at the
   extremal `p`-adic valuation must appear in pairs in any identity.
   Peeling all primes could bound the support of *primitive* identities.
   But this doesn't directly bound the *energy-weighted* short contribution.

3. **Anti-concentration / inverse Littlewood-Offord**: If many collisions
   exist, the denominator set has additive structure. Inverse Littlewood-Offord
   theory (Tao-Vu, Nguyen-Vu) gives GAP (generalized arithmetic progression)
   structure, but bridging from GAP structure to short identities requires
   new arguments.

4. **Coding-theoretic inverse lemma**: If many long kernel vectors exist,
   their differences might produce shorter vectors (analogous to the
   Gilbert-Varshamov bound). But differences of `{-1,0,1}` vectors may
   leave the `{-1,0,1}` alphabet.

### Computational evidence:

The conjecture is supported by exhaustive and sampling experiments for
`y ∈ {7, 11, 13}`, `k ≤ 12`, `N ≤ 70`. See `Smooth23Analysis.md` and
the experiment logs in the project documentation.

### Key open questions for experts:

1. Does the `{2,3}` S-unit equation classification extend to bounds on
   the Graver complexity of the smooth reciprocal kernel?
2. Can Evertse's theorem on S-unit equations give explicit support bounds
   for primitive identities with fixed prime set?
3. Is there a direct proof that smooth reciprocal kernels cannot have
   exponentially many long vectors without short ones?
-/
