import Mathlib
import RequestProject.Smooth23Completeness

/-!
# Support-4 Reciprocal Identities Among {2,3}-Smooth Integers

## Overview

We maintain a **computational catalogue** of support-4 reciprocal identity
cores: equations `a + b = c + d` where all four entries are positive coprime
{2,3}-smooth integers. Each core generates an infinite family of reciprocal
identities `1/d₁ + 1/d₂ = 1/d₃ + 1/d₄` via scaling.

## Catalogue status

**This is a computational catalogue, NOT a proved classification.**

- Exhaustive search with max entry ≤ 1,048,576 finds exactly **25 non-degenerate
  coprime cores** (all four entries distinct) and **3 degenerate cores** (with a
  repeated entry), for **28 total**.
- The catalogue is **stable**: the count does not change when extending the search
  bound from 1,024 to 1,048,576 (across 143 smooth numbers in range).
- **Completeness is conjectured but NOT proved.** A proof would require either an
  effective bound from Baker's method / linear forms in logarithms applied to the
  4-term {2,3} S-unit equation, or a complete enumeration using de Weger / Smart
  methods with a verified upper bound.

## Structural grouping

### Pattern 1: Anchor pair decomposition

Each core `a + b = c + d` can be decomposed as a "Pillai pair" `(2^α, 3^β)`
(with `2^α` and `3^β` on opposite sides) plus a "correction pair" `(x, y)` of
{2,3}-smooth integers with `|x - y| = |2^α - 3^β|`.

The gap `δ = |2^α - 3^β|` determines which corrections are available:
- **Gap 1** (Catalan pairs (4,3), (8,9)): 4+2 non-degenerate cores
- **Gap 5** (pairs (8,3), (4,9), (32,27)): 5 non-degenerate cores
- **Gap 7** (pair (16,9)): 1+1 cores
- **Gap 11** (pair (16,27)): 1 core
- **Gap 13** (pair (256,243)): 1 core
- **Gap 17** (pair (64,81)): 1 core
- **Gap 23** (pairs (4,27), (32,9)): 2 cores
- **Gap 47** (pair (128,81)): 1 core
- **Gap 431** (pair (512,81)): 1 core
- **Gap 485** (pair (512,27)): 1 core

Seven cores have no pure-power anchor (both pure powers on the same side).

### Pattern 2: Parametric families

The cores cluster into families generated by close pairs of consecutive
{2,3}-smooth numbers. The families are:
- **(8, 9) family** (gap 1): 3 cores with corrections (1,2), (2,3), (3,4)
- **(32, 27) family** (gap 5): 3 cores with corrections (1,6), (3,8), (4,9)
- **(4, 3) family** (gap 1): 1 non-degenerate core with correction (1,2)
- **(256, 243) family** (gap 13): 1 core with correction (3,16)
- Singletons from larger Pillai gaps

### Pattern 3: Correction pair structure

The correction pair `(x, y)` satisfies `y - x = δ` (the Pillai gap) and
both `x, y` are {2,3}-smooth with `gcd(2^α, 3^β, x, y) = 1`. For small
gaps, multiple corrections exist; for large gaps, at most one.

The number of non-degenerate cores is **finite** by Evertse's theorem on
S-unit equations, which bounds the number of non-degenerate solutions to
`a + b = c + d` in {2,3}-smooth integers.

## Complete catalogue

### Non-degenerate cores (25 total, all four entries distinct)

| # | Core (a,b,c,d) | a+b=c+d | Anchor pair | Gap |
|---|----------------|---------|-------------|-----|
| 1 | (4,1,3,2)      | 5       | (4,3)       | 1   |
| 2 | (6,1,4,3)      | 7       | —           | —   |
| 3 | (8,1,6,3)      | 9       | (8,3)       | 5   |
| 4 | (9,1,6,4)      | 10      | (4,9)       | 5   |
| 5 | (9,1,8,2)      | 10      | (8,9)       | 1   |
| 6 | (9,2,8,3)      | 11      | (8,9)       | 1   |
| 7 | (9,3,8,4)      | 12      | (8,9)       | 1   |
| 8 | (12,1,9,4)     | 13      | —           | —   |
| 9 | (16,1,9,8)     | 17      | (16,9)      | 7   |
| 10| (18,1,16,3)    | 19      | —           | —   |
| 11| (24,1,16,9)    | 25      | —           | —   |
| 12| (27,1,16,12)   | 28      | (16,27)     | 11  |
| 13| (27,1,24,4)    | 28      | (4,27)      | 23  |
| 14| (32,1,24,9)    | 33      | (32,9)      | 23  |
| 15| (32,1,27,6)    | 33      | (32,27)     | 5   |
| 16| (32,3,27,8)    | 35      | (32,27)     | 5   |
| 17| (32,4,27,9)    | 36      | (32,27)     | 5   |
| 18| (72,1,64,9)    | 73      | —           | —   |
| 19| (81,1,64,18)   | 82      | (64,81)     | 17  |
| 20| (96,1,81,16)   | 97      | —           | —   |
| 21| (128,1,81,48)  | 129     | (128,81)    | 47  |
| 22| (144,1,81,64)  | 145     | —           | —   |
| 23| (256,3,243,16) | 259     | (256,243)   | 13  |
| 24| (512,1,432,81) | 513     | (512,81)    | 431 |
| 25| (512,1,486,27) | 513     | (512,27)    | 485 |

### Degenerate cores (3 total, one repeated entry)

| # | Core (a,b,c,d) | a+b=c+d | Note |
|---|----------------|---------|------|
| D1| (3,1,2,2)      | 4       | 1/2 + 1/6 = 2/3 |
| D2| (4,2,3,3)      | 6       | 1/3 + 1/6 = 2/3 (equiv: support-3 with coeff 2) |
| D3| (16,2,9,9)     | 18      | 1/9 + 1/72 = 2/9 (equiv: support-3 with coeff 2) |

Degenerate cores correspond to `1/d₁ + 1/d₂ = 2/d₃` which are support-3
identities with coefficient 2, not true support-4 identities.
-/

open Finset BigOperators

/-! ## Section 1: Verified Base Identities (all 25 non-degenerate cores)

All identities verified by `norm_num`. Organized by structural group.
-/

/-! ### Group A: Gap-1 cores (Catalan pairs) -/

/-- Core #1 (4,1,3,2): anchor (4,3), gap 1. `1/3 + 1/12 = 1/4 + 1/6`. -/
theorem support4_core1 : (1 : ℚ) / 3 + 1 / 12 = 1 / 4 + 1 / 6 := by norm_num

/-- Core #5 (9,1,8,2): anchor (8,9), gap 1, correction (1,2).
    `1/8 + 1/72 = 1/9 + 1/36`. -/
theorem support4_core5 : (1 : ℚ) / 8 + 1 / 72 = 1 / 9 + 1 / 36 := by norm_num

/-- Core #6 (9,2,8,3): anchor (8,9), gap 1, correction (2,3).
    `1/8 + 1/36 = 1/9 + 1/24`. -/
theorem support4_core6 : (1 : ℚ) / 8 + 1 / 36 = 1 / 9 + 1 / 24 := by norm_num

/-- Core #7 (9,3,8,4): anchor (8,9), gap 1, correction (3,4).
    `1/8 + 1/24 = 1/9 + 1/18`. -/
theorem support4_core7 : (1 : ℚ) / 8 + 1 / 24 = 1 / 9 + 1 / 18 := by norm_num

/-! ### Group B: Gap-5 cores -/

/-- Core #3 (8,1,6,3): anchor (8,3), gap 5. `1/3 + 1/24 = 1/4 + 1/8`. -/
theorem support4_core3 : (1 : ℚ) / 3 + 1 / 24 = 1 / 4 + 1 / 8 := by norm_num

/-- Core #4 (9,1,6,4): anchor (4,9), gap 5. `1/4 + 1/36 = 1/6 + 1/9`. -/
theorem support4_core4 : (1 : ℚ) / 4 + 1 / 36 = 1 / 6 + 1 / 9 := by norm_num

/-- Core #15 (32,1,27,6): anchor (32,27), gap 5, correction (1,6).
    `1/27 + 1/864 = 1/32 + 1/144`. -/
theorem support4_core15 : (1 : ℚ) / 27 + 1 / 864 = 1 / 32 + 1 / 144 := by norm_num

/-- Core #16 (32,3,27,8): anchor (32,27), gap 5, correction (3,8).
    `1/27 + 1/288 = 1/32 + 1/108`. -/
theorem support4_core16 : (1 : ℚ) / 27 + 1 / 288 = 1 / 32 + 1 / 108 := by norm_num

/-- Core #17 (32,4,27,9): anchor (32,27), gap 5, correction (4,9).
    `1/27 + 1/216 = 1/32 + 1/96`. -/
theorem support4_core17 : (1 : ℚ) / 27 + 1 / 216 = 1 / 32 + 1 / 96 := by norm_num

/-! ### Group C: Gap-7 cores -/

/-- Core #9 (16,1,9,8): anchor (16,9), gap 7.
    `1/9 + 1/144 = 1/16 + 1/18`. -/
theorem support4_core9 : (1 : ℚ) / 9 + 1 / 144 = 1 / 16 + 1 / 18 := by norm_num

/-! ### Group D: Gap-11 core -/

/-- Core #12 (27,1,16,12): anchor (16,27), gap 11.
    `1/16 + 1/432 = 1/27 + 1/36`. -/
theorem support4_core12 : (1 : ℚ) / 16 + 1 / 432 = 1 / 27 + 1 / 36 := by norm_num

/-! ### Group E: Gap-13 core -/

/-- Core #23 (256,3,243,16): anchor (256,243), gap 13.
    `1/243 + 1/20736 = 1/256 + 1/3888`. -/
theorem support4_core23 : (1 : ℚ) / 243 + 1 / 20736 = 1 / 256 + 1 / 3888 := by norm_num

/-! ### Group F: Gap-17 core -/

/-- Core #19 (81,1,64,18): anchor (64,81), gap 17.
    `1/64 + 1/5184 = 1/81 + 1/288`. -/
theorem support4_core19 :
    (1 : ℚ) / 64 + 1 / 5184 = 1 / 81 + 1 / 288 := by norm_num

/-! ### Group G: Gap-23 cores -/

/-- Core #13 (27,1,24,4): anchor (4,27), gap 23.
    `1/8 + 1/216 = 1/9 + 1/54`. -/
theorem support4_core13 : (1 : ℚ) / 8 + 1 / 216 = 1 / 9 + 1 / 54 := by norm_num

/-- Core #14 (32,1,24,9): anchor (32,9), gap 23.
    `1/9 + 1/288 = 1/12 + 1/32`. -/
theorem support4_core14 : (1 : ℚ) / 9 + 1 / 288 = 1 / 12 + 1 / 32 := by norm_num

/-! ### Group H: Larger gap cores -/

/-- Core #21 (128,1,81,48): anchor (128,81), gap 47.
    `1/81 + 1/(128·81·48) = 1/128 + 1/(81·48)`. -/
theorem support4_core21 :
    (128 : ℤ) + 1 = 81 + 48 := by norm_num

/-- Core #21 reciprocal form: `1/(81·48) + 1/(128·81·48) = 1/(128·48) + 1/(128·81)`. -/
theorem support4_core21_recip :
    (1 : ℚ) / (81 * 48) + 1 / (128 * 81 * 48) = 1 / (128 * 48) + 1 / (128 * 81) := by norm_num

/-- Core #24 (512,1,432,81): anchor (512,81), gap 431. -/
theorem support4_core24 :
    (512 : ℤ) + 1 = 432 + 81 := by norm_num

/-- Core #24 reciprocal form. -/
theorem support4_core24_recip :
    (1 : ℚ) / (432 * 81) + 1 / (512 * 432 * 81) = 1 / (512 * 81) + 1 / (512 * 432) := by norm_num

/-- Core #25 (512,1,486,27): anchor (512,27), gap 485. -/
theorem support4_core25 :
    (512 : ℤ) + 1 = 486 + 27 := by norm_num

/-- Core #25 reciprocal form. -/
theorem support4_core25_recip :
    (1 : ℚ) / (486 * 27) + 1 / (512 * 486 * 27) = 1 / (512 * 27) + 1 / (512 * 486) := by norm_num

/-! ### Group I: Anchor-less cores (pure powers on same side) -/

/-- Core #2 (6,1,4,3): `1/2 + 1/12 = 1/3 + 1/4`. -/
theorem support4_core2 : (1 : ℚ) / 2 + 1 / 12 = 1 / 3 + 1 / 4 := by norm_num

/-- Core #8 (12,1,9,4): `1/3 + 1/36 = 1/4 + 1/9`. -/
theorem support4_core8 : (1 : ℚ) / 3 + 1 / 36 = 1 / 4 + 1 / 9 := by norm_num

/-- Core #10 (18,1,16,3): `1/8 + 1/144 = 1/9 + 1/48`. -/
theorem support4_core10 : (1 : ℚ) / 8 + 1 / 144 = 1 / 9 + 1 / 48 := by norm_num

/-- Core #11 (24,1,16,9): `1/6 + 1/144 = 1/9 + 1/16`. -/
theorem support4_core11 : (1 : ℚ) / 6 + 1 / 144 = 1 / 9 + 1 / 16 := by norm_num

/-- Core #18 (72,1,64,9): sum 73. -/
theorem support4_core18 :
    (72 : ℤ) + 1 = 64 + 9 := by norm_num

/-- Core #18 reciprocal form: `1/(64·9) + 1/(72·64·9) = 1/(72·9) + 1/(72·64)`. -/
theorem support4_core18_recip :
    (1 : ℚ) / (64 * 9) + 1 / (72 * 64 * 9) = 1 / (72 * 9) + 1 / (72 * 64) := by norm_num

/-- Core #20 (96,1,81,16): sum 97. -/
theorem support4_core20 :
    (96 : ℤ) + 1 = 81 + 16 := by norm_num

/-- Core #20 reciprocal form. -/
theorem support4_core20_recip :
    (1 : ℚ) / (81 * 16) + 1 / (96 * 81 * 16) = 1 / (96 * 16) + 1 / (96 * 81) := by norm_num

/-- Core #22 (144,1,81,64): sum 145. -/
theorem support4_core22 :
    (144 : ℤ) + 1 = 81 + 64 := by norm_num

/-- Core #22 reciprocal form. -/
theorem support4_core22_recip :
    (1 : ℚ) / (81 * 64) + 1 / (144 * 81 * 64) = 1 / (144 * 64) + 1 / (144 * 81) := by norm_num

/-! ### Degenerate cores (repeated entries) -/

/-- Degenerate core D1 (3,1,2,2): `1/2 + 1/6 = 2/3`. -/
theorem support4_degenerate1 : (1 : ℚ) / 2 + 1 / 6 = 2 / 3 := by norm_num

/-- Degenerate core D2 (4,2,3,3): `1/3 + 1/6 = 1/4 + 1/4`. -/
theorem support4_degenerate2 : (1 : ℚ) / 3 + 1 / 6 = 1 / 4 + 1 / 4 := by norm_num

/-- Degenerate core D3 (16,2,9,9): `1/9 + 1/72 = 1/16 + 1/16`. -/
theorem support4_degenerate3 : (1 : ℚ) / 9 + 1 / 72 = 1 / 16 + 1 / 16 := by norm_num

/-! ## Section 2: Parametric Scaling

Each coprime identity `1/a + 1/b = 1/c + 1/d` generates an infinite family
via scaling: `1/(ga) + 1/(gb) = 1/(gc) + 1/(gd)` for any positive `g`.
-/

/-- Scaling lemma: if `1/a + 1/b = 1/c + 1/d` then `1/(ga) + 1/(gb) = 1/(gc) + 1/(gd)`. -/
theorem support4_scaling (a b c d : ℕ) (g : ℕ) (hg : 0 < g)
    (ha : 0 < a) (hb : 0 < b) (hc : 0 < c) (hd : 0 < d)
    (hid : (1 : ℚ) / a + 1 / b = 1 / c + 1 / d) :
    (1 : ℚ) / (g * a) + 1 / (g * b) = 1 / (g * c) + 1 / (g * d) := by
  have hga : (g : ℚ) * a ≠ 0 := by positivity
  have hgb : (g : ℚ) * b ≠ 0 := by positivity
  have hgc : (g : ℚ) * c ≠ 0 := by positivity
  have hgd : (g : ℚ) * d ≠ 0 := by positivity
  field_simp at hid ⊢
  nlinarith

/-! ## Section 3: Primitivity (Graver Property)

A support-4 identity is **primitive** (a Graver basis element) if no proper
nonzero sub-relation with the same sign pattern exists. For a kernel vector
`(+1, +1, -1, -1)` on denominators `(d₁, d₂, d₃, d₄)`, this means no
proper subset admits a reciprocal identity with the same signs.
-/

/-- Core #1 (4,1,3,2) is primitive: no proper conformal sub-identity exists.
    Denominators: (3,12,4,6). -/
theorem support4_core1_primitive :
    (1 : ℚ) / 3 ≠ 1 / 4 ∧ (1 : ℚ) / 3 ≠ 1 / 6 ∧
    (1 : ℚ) / 12 ≠ 1 / 4 ∧ (1 : ℚ) / 12 ≠ 1 / 6 ∧
    (1 : ℚ) / 3 ≠ 1 / 4 + 1 / 6 ∧ (1 : ℚ) / 12 ≠ 1 / 4 + 1 / 6 ∧
    (1 : ℚ) / 3 + 1 / 12 ≠ 1 / 4 ∧ (1 : ℚ) / 3 + 1 / 12 ≠ 1 / 6 := by
  constructor <;> norm_num

/-- Core #5 (9,1,8,2) is primitive.
    Denominators: (8,72,9,36). -/
theorem support4_core5_primitive :
    (1 : ℚ) / 8 ≠ 1 / 9 ∧ (1 : ℚ) / 8 ≠ 1 / 36 ∧
    (1 : ℚ) / 72 ≠ 1 / 9 ∧ (1 : ℚ) / 72 ≠ 1 / 36 ∧
    (1 : ℚ) / 8 ≠ 1 / 9 + 1 / 36 ∧ (1 : ℚ) / 72 ≠ 1 / 9 + 1 / 36 ∧
    (1 : ℚ) / 8 + 1 / 72 ≠ 1 / 9 ∧ (1 : ℚ) / 8 + 1 / 72 ≠ 1 / 36 := by
  constructor <;> norm_num

/-- Core #6 (9,2,8,3) is primitive.
    Denominators: (8,36,9,24). -/
theorem support4_core6_primitive :
    (1 : ℚ) / 8 ≠ 1 / 9 ∧ (1 : ℚ) / 8 ≠ 1 / 24 ∧
    (1 : ℚ) / 36 ≠ 1 / 9 ∧ (1 : ℚ) / 36 ≠ 1 / 24 ∧
    (1 : ℚ) / 8 ≠ 1 / 9 + 1 / 24 ∧ (1 : ℚ) / 36 ≠ 1 / 9 + 1 / 24 ∧
    (1 : ℚ) / 8 + 1 / 36 ≠ 1 / 9 ∧ (1 : ℚ) / 8 + 1 / 36 ≠ 1 / 24 := by
  constructor <;> norm_num

/-- Core #7 (9,3,8,4) is primitive.
    Denominators: (8,24,9,18). -/
theorem support4_core7_primitive :
    (1 : ℚ) / 8 ≠ 1 / 9 ∧ (1 : ℚ) / 8 ≠ 1 / 18 ∧
    (1 : ℚ) / 24 ≠ 1 / 9 ∧ (1 : ℚ) / 24 ≠ 1 / 18 ∧
    (1 : ℚ) / 8 ≠ 1 / 9 + 1 / 18 ∧ (1 : ℚ) / 24 ≠ 1 / 9 + 1 / 18 ∧
    (1 : ℚ) / 8 + 1 / 24 ≠ 1 / 9 ∧ (1 : ℚ) / 8 + 1 / 24 ≠ 1 / 18 := by
  constructor <;> norm_num

/-! ## Section 4: Integer Core Reduction -/

/-- Denominator-clearing for support-4: `1/d₁ + 1/d₂ = 1/d₃ + 1/d₄`
    implies `d₃ · d₄ · (d₁ + d₂) = d₁ · d₂ · (d₃ + d₄)`. -/
lemma support4_clearing (d₁ d₂ d₃ d₄ : ℕ)
    (h1 : 0 < d₁) (h2 : 0 < d₂) (h3 : 0 < d₃) (h4 : 0 < d₄)
    (hid : (1 : ℚ) / d₁ + 1 / d₂ = 1 / d₃ + 1 / d₄) :
    d₃ * d₄ * (d₁ + d₂) = d₁ * d₂ * (d₃ + d₄) := by
  have hd1 : (d₁ : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr (by omega)
  have hd2 : (d₂ : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr (by omega)
  have hd3 : (d₃ : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr (by omega)
  have hd4 : (d₄ : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr (by omega)
  have key : (d₃ : ℚ) * d₄ * (d₁ + d₂) = d₁ * d₂ * (d₃ + d₄) := by
    field_simp at hid; nlinarith
  exact_mod_cast key

/-- Integer-core to reciprocal-identity conversion: given a valid integer
    core equation `a + b = c + d` with all terms positive, we get the
    reciprocal identity `1/(b·c·d) + 1/(a·c·d) = 1/(a·b·d) + 1/(a·b·c)`. -/
theorem intCore_to_recip_identity (a b c d : ℕ)
    (ha : 0 < a) (hb : 0 < b) (hc : 0 < c) (hd : 0 < d)
    (hsum : a + b = c + d) :
    (1 : ℚ) / (b * c * d) + 1 / (a * c * d) =
    (1 : ℚ) / (a * b * d) + 1 / (a * b * c) := by
  field_simp;
  norm_cast

/-! ## Section 5: Equivalence Relation -/

/-- Two 4-tuples of denominators are equivalent under the smooth scaling relation. -/
def support4Equiv (d₁ d₂ d₃ d₄ e₁ e₂ e₃ e₄ : ℕ) : Prop :=
  ∃ g : ℕ, 0 < g ∧ isSmooth 3 g ∧
    (  ({e₁, e₂} : Finset ℕ) = {g * d₁, g * d₂} ∧
      ({e₃, e₄} : Finset ℕ) = {g * d₃, g * d₄}
    ∨ ({e₁, e₂} : Finset ℕ) = {g * d₃, g * d₄} ∧
      ({e₃, e₄} : Finset ℕ) = {g * d₁, g * d₂})

/-- The coprime core of a 4-tuple: divide all entries by their gcd. -/
noncomputable def support4Core (d₁ d₂ d₃ d₄ : ℕ) : ℕ × ℕ × ℕ × ℕ :=
  let g := Nat.gcd (Nat.gcd (Nat.gcd d₁ d₂) d₃) d₄
  (d₁ / g, d₂ / g, d₃ / g, d₄ / g)

/-! ## Section 6: Verification of All Integer Core Sums -/

-- All 25 non-degenerate cores: a + b = c + d
example : ( 4 : ℤ) +  1 =  3 +  2 := by norm_num  -- Core #1
example : ( 6 : ℤ) +  1 =  4 +  3 := by norm_num  -- Core #2
example : ( 8 : ℤ) +  1 =  6 +  3 := by norm_num  -- Core #3
example : ( 9 : ℤ) +  1 =  6 +  4 := by norm_num  -- Core #4
example : ( 9 : ℤ) +  1 =  8 +  2 := by norm_num  -- Core #5
example : ( 9 : ℤ) +  2 =  8 +  3 := by norm_num  -- Core #6
example : ( 9 : ℤ) +  3 =  8 +  4 := by norm_num  -- Core #7
example : (12 : ℤ) +  1 =  9 +  4 := by norm_num  -- Core #8
example : (16 : ℤ) +  1 =  9 +  8 := by norm_num  -- Core #9
example : (18 : ℤ) +  1 = 16 +  3 := by norm_num  -- Core #10
example : (24 : ℤ) +  1 = 16 +  9 := by norm_num  -- Core #11
example : (27 : ℤ) +  1 = 16 + 12 := by norm_num  -- Core #12
example : (27 : ℤ) +  1 = 24 +  4 := by norm_num  -- Core #13
example : (32 : ℤ) +  1 = 24 +  9 := by norm_num  -- Core #14
example : (32 : ℤ) +  1 = 27 +  6 := by norm_num  -- Core #15
example : (32 : ℤ) +  3 = 27 +  8 := by norm_num  -- Core #16
example : (32 : ℤ) +  4 = 27 +  9 := by norm_num  -- Core #17
example : (72 : ℤ) +  1 = 64 +  9 := by norm_num  -- Core #18
example : (81 : ℤ) +  1 = 64 + 18 := by norm_num  -- Core #19
example : (96 : ℤ) +  1 = 81 + 16 := by norm_num  -- Core #20
example : (128 : ℤ) + 1 = 81 + 48 := by norm_num  -- Core #21
example : (144 : ℤ) + 1 = 81 + 64 := by norm_num  -- Core #22
example : (256 : ℤ) + 3 = 243+ 16 := by norm_num  -- Core #23
example : (512 : ℤ) + 1 = 432+ 81 := by norm_num  -- Core #24
example : (512 : ℤ) + 1 = 486+ 27 := by norm_num  -- Core #25

-- All 3 degenerate cores
example : (3 : ℤ) + 1 = 2 + 2 := by norm_num   -- Core D1
example : (4 : ℤ) + 2 = 3 + 3 := by norm_num   -- Core D2
example : (16 : ℤ) + 2 = 9 + 9 := by norm_num  -- Core D3

/-! ## Section 7: Support-4 Completeness Conjecture

**Conjecture (NOT proved).** The 28 coprime cores listed above (25 non-degenerate
+ 3 degenerate) form the COMPLETE list of coprime solutions to `a + b = c + d`
with all entries positive {2,3}-smooth integers.

### Evidence for completeness:
1. Exhaustive search is stable from max entry 1,024 to 1,048,576
   (tested at 1024, 2048, 4096, 8192, 16384, 65536, 262144, 1048576).
2. The search covers 143 distinct {2,3}-smooth numbers.
3. No new core has appeared since max entry 512.
4. Evertse's theorem guarantees finiteness of the complete list.

### What would be needed for a proof:
1. An effective upper bound on entries in coprime solutions, using Baker's method
   (linear forms in logarithms of 2 and 3).
2. Verification that the search bound exceeds this upper bound.
3. Alternatively, a complete solution using de Weger (1989) or Smart (1999)
   methods for S-unit equations with S = {2, 3}.

### Whether the 28 cores fall into finitely many parametric families:
**Yes, trivially**, since the list itself is finite (and conjecturally complete).
The more interesting question is whether the families have a clean parametric
description. The answer is partially yes:

- **Catalan-gap families**: Cores anchored by (2^α, 3^β) with |2^α - 3^β| = 1.
  By Catalan's conjecture (Mihailescu's theorem), the only pairs are
  (2,3), (4,3), (8,9). These generate 4 non-degenerate + 2 degenerate cores.
- **Small-gap families**: Cores from pairs with gap 5, generated by
  (8,3), (4,9), (32,27). These generate 5 non-degenerate cores.
- **Isolated cores**: Most larger-gap pairs generate exactly one core each
  (typically with correction (1, gap) or (3, gap+3)).
- **Anchor-less cores**: 7 cores where both pure powers land on the same
  side, arising from sums like 6+1=4+3 where 6=2·3 is mixed.
-/

/-- **Support-4 Completeness Conjecture** (S-unit classification).

    Every coprime solution `(a, b, c, d)` to `a + b = c + d` with all entries
    positive {2,3}-smooth appears in the catalogue of 28 cores.

    This is a finite computation by Evertse's theorem, but the explicit
    enumeration with a proved upper bound remains open. -/
theorem smooth23_four_term_sunit_finite :
    ∃ S : Finset (ℕ × ℕ × ℕ × ℕ),
    ∀ a b c d : ℕ,
      0 < a → 0 < b → 0 < c → 0 < d →
      isSmooth 3 a → isSmooth 3 b → isSmooth 3 c → isSmooth 3 d →
      a + b = c + d →
      Nat.gcd (Nat.gcd (Nat.gcd a b) c) d = 1 →
      a ≠ c → a ≠ d → b ≠ c → b ≠ d →
      (a, b, c, d) ∈ S := by
  -- Follows from Evertse's theorem on S-unit equations (1984)
  -- for S = {2, 3}. Complete enumeration is open.
  sorry

/-- **Support-4 Completeness** (reduced to S-unit classification).

    Every support-4 reciprocal identity `1/d₁ + 1/d₂ = 1/d₃ + 1/d₄`
    among distinct positive {2,3}-smooth integers belongs to one of
    finitely many families, each obtained by scaling a coprime core
    by a positive {2,3}-smooth factor. -/
theorem support4_completeness_of_smooth23
    (d₁ d₂ d₃ d₄ : ℕ)
    (h1 : 0 < d₁) (h2 : 0 < d₂) (h3 : 0 < d₃) (h4 : 0 < d₄)
    (hs1 : isSmooth 3 d₁) (hs2 : isSmooth 3 d₂)
    (hs3 : isSmooth 3 d₃) (hs4 : isSmooth 3 d₄)
    (hdist : d₁ ≠ d₂ ∧ d₁ ≠ d₃ ∧ d₁ ≠ d₄ ∧ d₂ ≠ d₃ ∧ d₂ ≠ d₄ ∧ d₃ ≠ d₄)
    (hid : (1 : ℚ) / d₁ + 1 / d₂ = 1 / d₃ + 1 / d₄) :
    ∃ (g a b c d : ℕ), 0 < g ∧ isSmooth 3 g ∧
      0 < a ∧ 0 < b ∧ 0 < c ∧ 0 < d ∧
      isSmooth 3 a ∧ isSmooth 3 b ∧ isSmooth 3 c ∧ isSmooth 3 d ∧
      Nat.gcd (Nat.gcd (Nat.gcd a b) c) d = 1 ∧
      a + b = c + d ∧
      ({d₁, d₂} : Finset ℕ) = {g * a, g * b} ∧
      ({d₃, d₄} : Finset ℕ) = {g * c, g * d} := by
  sorry
