import RequestProject.NANC.Gate1BDet2.ModulusSignCollapse

/-!
# Gate 1B / determinant-2 bank, Module 33: fixed-cell β twist recombination

This is the **exact algebra** behind the fixed-cell Dirichlet-polynomial
factorisation

  `D_χ(t) · P_χ(t) = ∑_q β_{D,P}(q) χ(q) q^{it}`,

with all analytic content (characters, Mellin transforms, the hybrid large
sieve) removed: the twist `χ(q) q^{it}` is replaced by an abstract
*multiplicative twist* `tau : ℕ → R` valued in a commutative ring `R`, and the
boxes are the fixed-cell `Finset`s `Dbox`, `Pbox` already used by
`ModulusSignCollapse` (Module 1).

Banked:

* `betaCell` — the fixed-cell convolution coefficient
  `β(q) = ∑_{d ∈ Dbox, p ∈ Pbox, d p = q} w_D(d) w_P(p)`;
* `qSupport` — the finite `q`-support built from the product of the boxes;
* `fixed_cell_recombination` — the exact twisted convolution identity;
* `fixed_cell_recombination_moebius_prime` — the specialisation
  `w_D = μ`, `w_P =` an abstract prime weight (no `Real.log` hard-coded).

**The hybrid large sieve is not formalized.**  A guard records that the
fixed-cell identity does **not** give global full-face recombination: the same
`q` receives different coefficients from different box pairs.
-/

namespace TwinPrimeProject
namespace Gate1BDet2
namespace FixedCell

open Finset ArithmeticFunction ArithmeticFunction.Moebius

variable {R : Type*} [CommRing R]

/-! ## 1. The fixed-cell convolution coefficient -/

/-- The finite `q`-support generated by a fixed cell: all products `d p` with
`d ∈ Dbox`, `p ∈ Pbox`. -/
def qSupport (Dbox Pbox : Finset ℕ) : Finset ℕ :=
  (Dbox ×ˢ Pbox).image (fun x => x.1 * x.2)

theorem mem_qSupport {Dbox Pbox : Finset ℕ} {q : ℕ} :
    q ∈ qSupport Dbox Pbox ↔ ∃ d ∈ Dbox, ∃ p ∈ Pbox, d * p = q := by
  classical
  simp [qSupport, Finset.mem_image, Finset.mem_product]
  aesop

/-- The fixed-cell convolution coefficient
`β(q) = ∑_{d ∈ Dbox, p ∈ Pbox, d p = q} w_D(d) w_P(p)`. -/
def betaCell (Dbox Pbox : Finset ℕ) (wd wp : ℕ → R) (q : ℕ) : R :=
  ∑ x ∈ (Dbox ×ˢ Pbox).filter (fun x => x.1 * x.2 = q), wd x.1 * wp x.2

/-! ## 2. The exact twisted convolution identity -/

/-- **Fixed-cell recombination.**  If the twist `tau` is multiplicative on all
admissible products `d p` (`d ∈ Dbox`, `p ∈ Pbox`), then

  `(∑_{d ∈ Dbox} w_D(d) τ(d)) · (∑_{p ∈ Pbox} w_P(p) τ(p))
      = ∑_{q ∈ qSupport} β(q) τ(q)`.

This is an exact finite identity in the commutative ring `R`. -/
theorem fixed_cell_recombination (Dbox Pbox : Finset ℕ) (wd wp tau : ℕ → R)
    (htau : ∀ d ∈ Dbox, ∀ p ∈ Pbox, tau (d * p) = tau d * tau p) :
    (∑ d ∈ Dbox, wd d * tau d) * (∑ p ∈ Pbox, wp p * tau p)
      = ∑ q ∈ qSupport Dbox Pbox, betaCell Dbox Pbox wd wp q * tau q := by
  classical
  set f : ℕ × ℕ → R := fun x => (wd x.1 * wp x.2) * tau (x.1 * x.2) with hf
  have hmaps : ∀ x ∈ Dbox ×ˢ Pbox, x.1 * x.2 ∈ qSupport Dbox Pbox := by
    intro x hx
    rw [Finset.mem_product] at hx
    exact mem_qSupport.2 ⟨x.1, hx.1, x.2, hx.2, rfl⟩
  have hleft : (∑ d ∈ Dbox, wd d * tau d) * (∑ p ∈ Pbox, wp p * tau p)
      = ∑ x ∈ Dbox ×ˢ Pbox, f x := by
    rw [Finset.sum_mul_sum, ← Finset.sum_product']
    refine Finset.sum_congr rfl (fun x hx => ?_)
    rw [Finset.mem_product] at hx
    rw [hf]
    simp only
    rw [htau x.1 hx.1 x.2 hx.2]
    ring
  have hright : ∑ q ∈ qSupport Dbox Pbox, betaCell Dbox Pbox wd wp q * tau q
      = ∑ q ∈ qSupport Dbox Pbox, ∑ x ∈ (Dbox ×ˢ Pbox).filter (fun x => x.1 * x.2 = q), f x := by
    refine Finset.sum_congr rfl (fun q _ => ?_)
    rw [betaCell, Finset.sum_mul]
    refine Finset.sum_congr rfl (fun x hx => ?_)
    rw [Finset.mem_filter] at hx
    rw [hf]
    simp only [hx.2]
  rw [hleft, hright, Finset.sum_fiberwise_of_maps_to hmaps f]

/-! ## 3. Specialisation: Möbius times an abstract prime weight -/

/-- The Möbius / prime-weight fixed-cell coefficient
`β(q) = ∑_{d p = q} μ(d) w(p)`, with `w` an abstract ring-valued prime weight
(no `Real.log` is hard-coded). -/
def betaMoebiusPrime (Dbox Pbox : Finset ℕ) (w : ℕ → R) (q : ℕ) : R :=
  betaCell Dbox Pbox (fun d => ((μ d : ℤ) : R)) w q

/-- **Specialised recombination.**  `D(τ) · P(τ) = ∑_q β_{μ,w}(q) τ(q)`. -/
theorem fixed_cell_recombination_moebius_prime (Dbox Pbox : Finset ℕ) (w tau : ℕ → R)
    (htau : ∀ d ∈ Dbox, ∀ p ∈ Pbox, tau (d * p) = tau d * tau p) :
    (∑ d ∈ Dbox, ((μ d : ℤ) : R) * tau d) * (∑ p ∈ Pbox, w p * tau p)
      = ∑ q ∈ qSupport Dbox Pbox, betaMoebiusPrime Dbox Pbox w q * tau q :=
  fixed_cell_recombination Dbox Pbox _ w tau htau

/-! ## 4. Guard: fixed-cell ≠ full-face recombination -/

/-- **GUARD.**  Fixed-cell recombination does *not* give global (full-face)
recombination: the coefficient attached to a given `q` depends on the cell.  For
`q = 2` the cell `({1}, {2})` gives `β(2) = 1`, while the larger cell
`({1,2}, {1,2})` gives `β(2) = 2`. -/
theorem fixed_cell_recombination_does_not_imply_full_face_recombination :
    betaCell ({1} : Finset ℕ) ({2} : Finset ℕ) (fun _ => (1 : ℤ)) (fun _ => 1) 2
      ≠ betaCell ({1, 2} : Finset ℕ) ({1, 2} : Finset ℕ) (fun _ => (1 : ℤ)) (fun _ => 1) 2 := by
  unfold betaCell
  decide

end FixedCell
end Gate1BDet2
end TwinPrimeProject
